Import('*')

SimObject('HelloObject.py')
Source('hello_object.cc')
Source('goodbye_object.cc')
DebugFlag('Hello')

SimObject('SimpleMemobj.py')
Source('simple_memobj.cc')
DebugFlag('SimpleMemobj')

SimObject('SimpleCache.py')
Source('simple_cache.cc')
DebugFlag('SimpleCache')
